# Generated by Django 5.2.11 on 2026-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('average_price', models.FloatField()),
                ('median_price', models.FloatField()),
                ('confidence_interval_lower', models.FloatField()),
                ('confidence_interval_upper', models.FloatField()),
                ('sample_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
