# Generated by Django 5.2.11 on 2026-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_priceanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceanalysis',
            name='currency',
            field=models.CharField(default='EUR', max_length=255),
            preserve_default=False,
        ),
    ]
