# Generated by Django 6.0.4 on 2026-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_priceanalysis_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='city',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
