// export const cityCodes = {
//     // North America
//     "New York": "NYC",
//     "Los Angeles": "LAX",
//     "Chicago": "ORD",
//     "Miami": "MIA",
//     "San Francisco": "SFO",
//     "Las Vegas": "LAS",
//     "Boston": "BOS",
//     "Toronto": "YTO",
//     "Vancouver": "YVR",
//     "Mexico City": "MEX",
//
//     // Europe
//     "Skopje": "SKP",
//     "Paris": "PAR",
//     "London": "LON",
//     "Rome": "ROM",
//     "Milan": "MIL",
//     "Barcelona": "BCN",
//     "Madrid": "MAD",
//     "Berlin": "BER",
//     "Munich": "MUC",
//     "Amsterdam": "AMS",
//     "Brussels": "CRL",
//     "Vienna": "VIE",
//     "Zurich": "ZRH",
//     "Lisbon": "LIS",
//     "Athens": "ATH",
//     "Prague": "PRG",
//     "Budapest": "BUD",
//     "Dublin": "DUB",
//     "Copenhagen": "CPH",
//     "Oslo": "OSL",
//     "Stockholm": "STO",
//     "Helsinki": "HEL",
//     "Warsaw": "WAW",
//     "Istanbul": "IST",
//
//     // Asia
//     "Tokyo": "TYO",
//     "Osaka": "OSA",
//     "Seoul": "SEL",
//     "Beijing": "BJS",
//     "Shanghai": "SHA",
//     "Hong Kong": "HKG",
//     "Bangkok": "BKK",
//     "Singapore": "SIN",
//     "Kuala Lumpur": "KUL",
//     "New Delhi": "DEL",
//     "Mumbai": "BOM",
//     "Dubai": "DXB",
//
//     // Oceania
//     "Sydney": "SYD",
//     "Melbourne": "MEL",
//     "Auckland": "AKL",
//
//     // South America
//     "Buenos Aires": "BUE",
//     "Rio de Janeiro": "RIO",
//     "Sao Paulo": "SAO",
//     "Lima": "LIM",
//     "Santiago": "SCL",
//     "Bogota": "BOG",
//
//     // Africa
//     "Cairo": "CAI",
//     "Johannesburg": "JNB",
//     "Cape Town": "CPT",
//     "Casablanca": "CMN",
// }

export const cityCodes = {
  "Tirana": "TIA",
  "Gyumri": "LWN",
  "Yerevan": "EVN",
  "Baku": "GYD",
  "Brussels": "BRU",
  "Banja Luka": "BNX",
  "Sarajevo": "SJJ",
  "Tuzla": "TZL",
  "Bourgas": "BOJ",
  "Plovdiv": "PDV",
  "Sofia": "SOF",
  "Varna": "VAR",
  "Dubrovnik": "DBV",
  "Rijeka": "RJK",
  "Split": "SPU",
  "Zadar": "ZAD",
  "Larnaca": "LCA",
  "Paphos": "PFO",
  "Prague": "PRG",
  "Billund": "BLL",
  "Copenhagen": "CPH",
  "Alexandria": "HBE",
  "Cairo": "SPX",
  "Hurghada": "HRG",
  "Marsa Alam": "RMF",
  "Sharm El Sheikh": "SSH",
  "Tallinn": "TLL",
  "Turku": "TKU",
  "Basel": "BSL",
  "Bordeaux": "BOD",
  "Grenoble": "GNB",
  "Lyon": "LYS",
  "Nice": "NCE",
  "Paris": "PAR",
  "Kutaisi": "KUT",
  "Berlin": "BER",
  "Cologne": "CGN",
  "Dortmund": "DTM",
  "Frankfurt": "FRA",
  "Friedrichshafen": "FDH",
  "Hamburg": "HAM",
  "Karlsruhe/Baden-Baden": "FKB",
  "Munich": "MUC",
  "Nuremberg": "NUE",
  "Stuttgart": "STR",
  "Athens": "ATH",
  "Chania": "CHQ",
  "Corfu": "CFU",
  "Heraklion": "HER",
  "Kalamata": "KLX",
  "Kefalonia": "EFL",
  "Mykonos": "JMK",
  "Rhodes": "RHO",
  "Santorini": "JTR",
  "Skiathos": "JSI",
  "Thessaloniki": "SKG",
  "Zakynthos": "ZTH",
  "Budapest": "BUD",
  "Debrecen": "DEB",
  "Reykjavik": "KEF",
  "Tel-Aviv": "TLV",
  "Alghero": "AHO",
  "Ancona": "AOI",
  "Bari": "BRI",
  "Bologna": "BLQ",
  "Brindisi": "BDS",
  "Catania": "CTA",
  "Comiso": "CIY",
  "Genoa": "GOA",
  "Lamezia Terme": "SUF",
  "Lampedusa": "LMP",
  "Milan": "MIL",
  "Naples": "NAP",
  "Olbia": "OLB",
  "Palermo": "PMO",
  "Perugia": "PEG",
  "Pescara": "PSR",
  "Pisa": "PSA",
  "Rimini": "RMI",
  "Rome": "ROM",
  "Trieste": "TRS",
  "Turin": "TRN",
  "Venice": "VEN",
  "Verona": "VRN",
  "Amman": "AMM",
  "Prishtina": "PRN",
  "Kaunas": "KUN",
  "Palanga": "PLQ",
  "Vilnius": "VNO",
  "Malta": "MLA",
  "Chisinau": "RMO",
  "Podgorica": "TGD",
  "Agadir": "AGA",
  "Marrakesh": "RAK",
  "Eindhoven": "EIN",
  "Maastricht": "MST",
  "Ohrid": "OHD",
  "Skopje": "SKP",
  "Alesund": "AES",
  "Bergen": "BGO",
  "Haugesund": "HAU",
  "Oslo": "OSL",
  "Sandefjord": "TRF",
  "Stavanger": "SVG",
  "Tromso": "TOS",
  "Trondheim": "TRD",
  "Gdansk": "GDN",
  "Katowice": "KTW",
  "Krakow": "KRK",
  "Lublin": "LUZ",
  "Olsztyn-Mazury": "SZY",
  "Poznan": "POZ",
  "Rzeszow": "RZE",
  "Szczecin": "SZZ",
  "Warsaw": "WAW",
  "Wroclaw": "WRO",
  "Faro": "FAO",
  "Funchal": "FNC",
  "Lisbon": "LIS",
  "Porto": "OPO",
  "Bacau": "BCM",
  "Brasov": "GHV",
  "Bucharest": "BUH",
  "Cluj-Napoca": "CLJ",
  "Constanta": "CND",
  "Craiova": "CRA",
  "Iasi": "IAS",
  "Oradea": "OMR",
  "Satu Mare": "SUJ",
  "Sibiu": "SBZ",
  "Suceava": "SCV",
  "Targu Mures": "TGM",
  "Timisoara": "TSR",
  "Jeddah": "JED",
  "Medina": "MED",
  "Belgrade": "BEG",
  "Nis": "INI",
  "Bratislava": "BTS",
  "Kosice": "KSC",
  "Poprad-Tatry": "TAT",
  "Ljubljana": "LJU",
  "Alicante": "ALC",
  "Barcelona": "BCN",
  "Bilbao": "BIO",
  "Castellon": "CDT",
  "Fuerteventura": "FUE",
  "Gran Canaria": "LPA",
  "Ibiza": "IBZ",
  "Madrid": "MAD",
  "Malaga": "AGP",
  "Menorca": "MAH",
  "Palma de Mallorca": "PMI",
  "Santander": "SDR",
  "Seville": "SVQ",
  "Tenerife": "TFS",
  "Valencia": "VLC",
  "Zaragoza": "ZAZ",
  "Gothenburg": "GOT",
  "Malmo": "MMX",
  "Stockholm": "STO",
  "Ankara": "ESB",
  "Antalya": "AYT",
  "Dalaman": "DLM",
  "Istanbul": "IST",
  "Abu Dhabi": "AUH",
  "Dubai": "DXB",
  "Aberdeen": "ABZ",
  "Birmingham": "BHX",
  "Glasgow": "GLA",
  "Leeds": "LBA",
  "Liverpool": "LPL",
  "London": "LON"
}